# Generated by Django 5.0.6 on 2024-10-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
